apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: loading-dock-builder
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          maxRetries: 0
          timeoutSeconds: 3600
          containers:
            - image: IMAGE_URL
              env:
                - name: BUILD_PLATFORM
                  value: android
                - name: BUILD_PROFILE
                  value: preview
                - name: BUILD_OUTPUT_DIRECTORY
                  value: /builds/output
                - name: BUILD_WORKSPACE_DIRECTORY
                  value: /build
                - name: BUILD_MAX_RAM_USAGE
                  value: "4g"
                - name: RUN_EXPO_DOCTOR
                  value: "true"
              volumeMounts:
                - name: build-tmp
                  mountPath: /tmp
              resources:
                limits:
                  cpu: "4"
                  memory: 16Gi
          volumes:
            - name: build-tmp
              emptyDir:
                medium: Disk
                sizeLimit: 32Gi
