apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: loading-dock-builder
spec:
  template:
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          maxRetries: 0
          timeoutSeconds: 3600
          containers:
            - image: europe-north1-docker.pkg.dev/main-api-server/loading-dock/loading-dock-builder:latest
              env:
                - name: BUILD_PLATFORM
                  value: android
                - name: BUILD_PROFILE
                  value: preview
                - name: BUILD_OUTPUT_DIRECTORY
                  value: /builds/output
                - name: BUILD_WORKSPACE_DIRECTORY
                  value: /build
                - name: BUILD_MAX_RAM_USAGE
                  value: "4g"
                - name: RUN_EXPO_DOCTOR
                  value: "true"
                - name: NPM_CONFIG_CACHE
                  value: /root/.npm
                - name: TMPDIR
                  value: /tmp
              resources:
                limits:
                  cpu: "4"
                  memory: 16Gi
              volumeMounts:
                - name: build-tmp
                  mountPath: /build
                - name: build-tmp
                  mountPath: /root/.gradle
                - name: build-tmp
                  mountPath: /root/.npm
                - name: build-tmp
                  mountPath: /tmp
          volumes:
            - name: build-tmp
              emptyDir:
                medium: Memory
                sizeLimit: 8Gi
